export const SET_THEME_LIGHT = "SET_THEME_LIGHT";
export const SET_THEME_DARK = "SET_THEME_DARK";
export const SET_SIDEBAR_PANEL_ACTIVE = "SET_SIDEBAR_PANEL_ACTIVE";
export const SET_SIDEBAR_PANEL_INACTIVE = "SET_SIDEBAR_PANEL_INACTIVE";
export const SET_TENANT_DATA = "SET_TENANT_DATA";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_ACCOUNTINFO_DATA = "SET_ACCOUNTINFO_DATA";
export const SET_SUBSCRIPTION_DATA = "SET_SUBSCRIPTION_DATA";
export const SET_HAS_NEW_SUBSCRIPTION_MODAL_OPENED =
  "SET_HAS_NEW_SUBSCRIPTION_MODAL_OPENED";
